### ISSUE TITLE
Long Press Enter: Change IME doesn't work anymore

### ISSUE THREAD

**Issue by francwalter** [Danation/SwypeTweaks#2]
Hello

since the update of Swype to version 2.0.0.2000050.38944 last week the long press on the Enter key is not anymore usable to change the keyboard. 
In the SwypeTweaks 1.4 settings:
**OTHER > Long Press Enter: Change IME (e.g. Google Voice Recognition).**
Swype has now an own long-press event: popup of choose between enter and emojii, which is good by the way.
So a long-press on enter is not anymore hooked by SwypeTweaks.
I looked into the code and found in the method "longPressEnterChangeIME" this line:

``` java
final int ENTER_CODE = 10;
```

So could it not just be very easy to change the thing by using the Dragon Button (long press on it) for the change? Don't know the code number for it, though.
This would by the way be more intuitive, as it is already a Text-Recognition-Button.
It would be necessary then for the user, not to disable it in the Swype settings (where it can be disabled).

At the moment only way to get at least Google voice recognition is the first setting:
**Google or Dragon? (reboot)** 
but not possible now to set an own keyboard like before.

Thanks for fixing it hopely :)

frank

**Comment by Danation** [comment]
I'll look into it.

**Comment by francwalter** [comment]
Dragon Button is code 6463 as netkaion mentioned here in a [comment about SwypeTweaks.java
](https://github.com/Danation/SwypeTweaks/commit/4cafe714637ac8813541fd58061c25f9790bc424#commitcomment-13066563)
So **I** think this is the best solution.

**Comment by Danation** [comment]
Ok, I will do that.

**Comment by Danation** [comment]
Alright, I used the Speech Key (Dragon Button, Microphone Button) as you suggested.  Thanks for following up on that.
