### ISSUE TITLE
No instruction how to compile

### ISSUE THREAD

**Issue by francwalter** [Danation/SwypeTweaks#3]
Hello
in order to give other developer a chance to fastly build this nice Xposed module, without long search of missing libraries, at least a short intro how to compile would be nice.
Necessary libraries, which IDE etc.
Unfortunately this great module is rarely updated, new developer could help here by fixing etc.

Thanks.

frank

**Comment by Danation** [comment]
This is a standard and very vanilla Android project.  If you are at all familiar with Android development, compilation is no different than other Android projects.

**Comment by francwalter** [comment]
I will put later some little instructions in the wiki.
