### ISSUE TITLE
Unnecessary Debug entries in Xposed log

### ISSUE THREAD

**Issue by francwalter** [Danation/SwypeTweaks#5]
There are debug messages in the Xposed logfile.
I think there should be no messages if there is no error. 
In my Xposed log the only entries in the logfile after boot is from SwypeTweaks.
After too long, the log will be filled.

**Comment by Danation** [comment]
Please provide evidence that log entries can have a negative impact.

**Comment by francwalter** [comment]
I am not sure if the Xposed logfile is still readable after a week when it is filled with SwypeTweak debug messages, for no purpose.
It irritates me, that there are log entries, only from SwypeTweaks and none of my many much bigger and much more complex modules (e.g. XPrivacy) don't write any line if there is not any error.
As I understand, the Xposed log is only for errors, not for debug messages (e.g. SwypeTweaks started, SwypeTweaks did this, SwypeTweaks did that etc. - this is loglevel debug or info but not error or at least warning)
I think this is just "best practice" to stop filling the log, when the beta testing is over and all works well.

EDIT: It is only three lines in the main java File "SwypeTweaks.java", line 26, 119, 123.
I commented them out and off this goes. I guess you don't need a pull request for this?

**Comment by Danation** [comment]
Honestly, this is a non-issue.  A log is meant for logging.  Logging is occurring.  Everything is fine.

Maybe in the future I'll add an option to enable/disable logging, but it's a very low priority.
